apiVersion: apps/v1
#kind: StatefulSet
kind: Deployment
metadata:
  namespace: tomcat
  name: tomcat-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      tier: postgres
  template:
    metadata:
      labels:
        app: app
        tier: postgres
    spec:
      containers:
        - name: tomcat-9
          image: tomcat:9.0
          command: ["/bin/sh","-c"]
          args: ["printf '%s' $API_TOKEN > $SA_TOKEN_FILE  && catalina.sh run"]
          volumeMounts:
            - mountPath: /usr/local/tomcat/conf/server.xml
              subPath: server.xml
              readOnly: true
              name: serverxml
            
            - mountPath: /usr/local/tomcat/webapps
              name: tomcat-data

          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          env:
          - name: SA_TOKEN_FILE
            value: /usr/local/tokenFile   
          - name: KUBERNETES_NAMESPACE
            value: tomcat 
          - name: API_TOKEN
            valueFrom:
              secretKeyRef:
                name: "api-access-token"
                key: "token"
      volumes:
        - name: serverxml
          configMap:
            name: testconfig
        - name: tomcat-data
          persistentVolumeClaim:
            claimName: tomcat-pvc
